import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/context/ThemeProvider";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
	title: "SchoolHub",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${montserrat.className} min-h-screen bg-background antialiased`}
				>
					<main className="min-h-screen w-full dark:bg-dark text-dark dark:text-white bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative">
						<div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-dark bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_85%,black)]" />
						<ThemeProvider>{children}</ThemeProvider>
					</main>
				</body>
			</html>
		</ClerkProvider>
	);
}
